# Local snapshot rules
snap:
  - name: home
    path: /home/rqdmap
    rules:
      - period: 1d
        cnt: 7
      - period: 7d
    sync:
      method: local                 # local, ssh, file
      path: /mnt/archlinux/home

  - name: data
    path: /data/rqdmap
    rules:
      - period: 1d
        cnt: 7
      - period: 7d
    sync:
      method: local
      path: /mnt/archlinux/data

  - name: root
    path: /real_root/@
    rules:
      - period: 1d
    sync:
      method: local
      path: /mnt/archlinux/root

sync:
  target:
    - host: mac.rqdmap.top
      port: 22
      user: root
      identity_file: /home/rqdmap/.ssh/id_ed25519
    - host: $TARGET_IPV6          # Support ENV var
      port: 22
      user: root
      identity_file: /home/rqdmap/.ssh/id_ed25519
    - host: localhost
      port: 60022
      user: root
      identity_file: /home/rqdmap/.ssh/id_ed25519
  pre_hook:
    - mount ...
  post_hook:
    - umount ...

